[138] - Change_password_for_registered_user - Implement password reset fu…
GreenCityProject/GreenCityUser21_team_1_May pull request #42
Opened 2024-06-04 12:07 UTC by RockTF

…nctionality

Added the ability for users to reset their passwords for the OwnSecurity service. This includes new validation checks for the reset process and accompanying unit tests to ensure functionality correctness. Also updated the security configuration and respective controllers to handle the password reset endpoints.

2024-06-09 17:42 UTC, tellmant requested changes
## Recommended changes:
1. Change response status for the **updateCurrentPassword** endpoint from **201 (Created)** to **200 (Ok)**

## Required changes:
1. Handle the case where a user attempts to enter the same password as the old one. Currently, this results in an **Internal Server Error (500)**, which should be handled properly.
   > *Example:*
   >
   > ![image](https://github.com/GreenCityProject/GreenCityUser21_team_1_May/assets/128901331/1bc670a6-c925-4b62-9686-9413587ef404)

2024-06-09 17:42 UTC, tellmant commented on core/src/main/java/greencity/security/controller/OwnSecurityController.java
It would be better to change the response status for password reset from `HttpStatus.CREATED (201)` to `HttpStatus.OK (200)` for the `updateCurrentPassword` endpoint.

2024-06-12 04:39 UTC, RockTF commented on core/src/main/java/greencity/security/controller/OwnSecurityController.java
This is the correct answer for a Post request)

2024-06-12 04:40 UTC, RockTF commented on core/src/main/java/greencity/security/controller/OwnSecurityController.java
But you are right about the 500 status. It seems I didn't add a handler for the custom exception in our error handler.

2024-06-18 09:48 UTC, closed without merging